// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYafwVZzUz8ZLWD7NUZpVxvez2pUgfS68',
    appId: '1:140001101863:web:c05ceb917e997db58d6602',
    messagingSenderId: '140001101863',
    projectId: 'tripmatic-5a707',
    authDomain: 'tripmatic-5a707.firebaseapp.com',
    storageBucket: 'tripmatic-5a707.firebasestorage.app',
    measurementId: 'G-Y4GQFCFB0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUR5rnGzzQLn8kTEBtPdePkBU6u4m7DQc',
    appId: '1:140001101863:android:5a08891e025bc4238d6602',
    messagingSenderId: '140001101863',
    projectId: 'tripmatic-5a707',
    storageBucket: 'tripmatic-5a707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTooIRaxmCXvR8bEcI9I5fz93pX2o2RtA',
    appId: '1:915286640896:ios:dacbedcdab3b15c1ce8be5',
    messagingSenderId: '915286640896',
    projectId: 'homepalette-f5fa7',
    storageBucket: 'homepalette-f5fa7.firebasestorage.app',
    iosBundleId: 'com.example.finalProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTooIRaxmCXvR8bEcI9I5fz93pX2o2RtA',
    appId: '1:915286640896:ios:dacbedcdab3b15c1ce8be5',
    messagingSenderId: '915286640896',
    projectId: 'homepalette-f5fa7',
    storageBucket: 'homepalette-f5fa7.firebasestorage.app',
    iosBundleId: 'com.example.finalProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYafwVZzUz8ZLWD7NUZpVxvez2pUgfS68',
    appId: '1:140001101863:web:a05cf3d732c4f0388d6602',
    messagingSenderId: '140001101863',
    projectId: 'tripmatic-5a707',
    authDomain: 'tripmatic-5a707.firebaseapp.com',
    storageBucket: 'tripmatic-5a707.firebasestorage.app',
    measurementId: 'G-DR0J0X0NVD',
  );

}